#!/usr/bin/env bash
set -eu
cd "$(dirname "$0")"

OUT=hydra.sh
{
  echo '#!/usr/bin/env bash'
  echo '# AUTO-GENERATED by build.sh — DO NOT EDIT.'
  cat lib/boot.sh lib/hmac.sh lib/primitives.sh lib/guards.sh main.sh \
    | grep -vE '^#!/usr/bin/env bash$|^#!/bin/bash$'
} > "$OUT"
chmod +x "$OUT"

if command -v shellcheck >/dev/null 2>&1; then
  shellcheck "$OUT" || { echo "shellcheck failed"; exit 1; }
fi

NCNB=$(grep -cvE '^\s*(#|$)' "$OUT")
if [ "$NCNB" -gt 200 ]; then
  echo "ERROR: hydra.sh has $NCNB non-comment lines (cap 200)"; exit 1
fi
echo "built $OUT — $NCNB non-comment lines"
